### ISSUE TITLE
Support GLSL 110 syntax

### ISSUE THREAD

**Issue by KubaP** [KubaP/glsl-lsp#21]
Currently we are targetting GLSL 450/460, but the default version for any GL source string that lacks the `#version` directive is GLSL 110, so it would be good to properly support this variant.

### Tasks
- [ ] Implement entry points into the lexer to allow consumers to choose between dynamically detecting the GLSL version or hardcoding the version.
- [ ] Implement scaffolding in the lexer to detect the GLSL version whilst scanning the file, and switch appropriately (currently switching won't do anything).
- [ ] Read the GLSL 110 specification and compare against the GLSL 450 specification for any differences.
- [ ] Figure out how to divide and organize the existing lexing and parsing logic in such a way as to minimize duplication but retain clarity between which functions apply for which language version.
- [ ] Actually implement the necessary changes to the lexer and parser.
